version: '3'

networks:
  mynetwork:
    driver: bridge


services: 
  db:
    build: ./requirements/mariadb
    environment:
      DB_NAME: mydatabase
      DB_USER: myuser
      MYSQL_ROOT_PASSWORD: mysecretpassword
      DB_PASS: mypassword
    volumes:
      - mariadb-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  wordpress:
    build: ./requirements/wordpress
    environment:
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASS: mypassword
      DB_HOST: db
    volumes:
      - wrd-nginx-volume:/var/www/html
    ports:
      - "9000:9000"
    restart: always
    depends_on:
         - db
    networks:
      - mynetwork

  nginx:
    build:
      context: ./requirements/nginx
    volumes:
      - wrd-nginx-volume:/var/www/html
    ports:
      - "80:80"
    restart: always
    depends_on:
      - wordpress
    networks:
      - mynetwork

volumes:
  mariadb-volume:
  wrd-nginx-volume:
