version: '3'

volumes:
  mariadb-volume:
  # wordpress-volume:

services: 
  db: 
    environment:
      - "DB_NAME=mydatabase"
      - "DB_USER=myuser"
      - "DB_PASS=mypassword"
    build: ./requirements/mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql
    # ports:
    #   - "3306:3306"
  web:
    build: ./requirements/wordpress
    environment:
      - "DB_NAME=mydatabase"
      - "DB_USER=myuser"
      - "DB_PASS=mypassword"
      - "DB_HOST=mariadb"
    volumes:
      - wordpress-volume:/var/www/html
    depends_on:
      - db


