version: '3'

services: 
  db:
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - mynetwork


  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wrd-nginx-volume:/var/www/html
    ports:
      - 9000:9000
    restart: always
    depends_on:
      - db
    networks:
      - mynetwork


  nginx:
    build:
      context: ./requirements/nginx
    volumes:
      - wrd-nginx-volume:/var/www/html
    ports:
      - 443:443
    restart: always
    depends_on:
      - wordpress
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge

volumes:
  mariadb-volume:
  wrd-nginx-volume:
