version: '3'

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/iouazzan/data/db
  wrd-nginx-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/iouazzan/data/wdp

services:
  db:
    build: ./requirements/mariadb
    image: db
    env_file:
      - .env
    restart: always
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - mynetwork


  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    env_file:
      - .env
    volumes:
      - wrd-nginx-volume:/var/www/html
    restart: always
    depends_on:
      - db
    networks:
      - mynetwork


  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    volumes:
      - wrd-nginx-volume:/var/www/html
    ports:
      - 443:443
    restart: always
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge
