version: '3'

services: 
  db:
    build: ./requirements/mariadb
    environment:
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASS: mypassword
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - mynetwork
    init : true

  wordpress:
    build: ./requirements/wordpress
    environment:
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASS: mypassword
      DB_HOST: db
    volumes:
      - wrd-nginx-volume:/var/www/html
    ports:
      - 9000:9000
    restart: always
    depends_on:
         - db
    networks:
      - mynetwork
    init : true

  nginx:
    build:
      context: ./requirements/nginx
    volumes:
      - wrd-nginx-volume:/var/www/html
    ports:
      - 443:443
    restart: always
    depends_on:
      - wordpress
    networks:
      - mynetwork
    init : true

networks:
  mynetwork:
    driver: bridge

volumes:
  mariadb-volume:
  wrd-nginx-volume:
